all:
	gcc -Wall -pedantic -std=c99 src/main.c src/userInput.c src/draw.c -lncurses -lm -Iinclude -o bin/runMe

debug:
	gcc -Wall -pedantic -std=c99 -g src/main.c src/userInput.c src/draw.c -lncurses -lm -Iinclude -o bin/runMe
